[tool.ruff]
line-length = 120
select = ["E", "F", "I", "UP"]
ignore = ["D203"]
extend-exclude = ["src/flaskapp/migrations/"]

[tool.ruff.isort]
{% if cookiecutter.project_backend == "flask" %}
known-first-party = ["flaskapp"]
{% endif %}
{% if cookiecutter.project_backend == "fastapi" %}
known-first-party = ["fastapi_app"]
{% endif %}

[tool.pytest.ini_options]
addopts = "-ra -vv"
{% if cookiecutter.project_backend == "django" %}
DJANGO_SETTINGS_MODULE = "project.settings"
pythonpath = ["src"]
{% endif %}
