[tool.ruff]
line-length = 120
target-version = "py38"
select = ["E", "F", "I", "UP"]
ignore = ["D203"]

[tool.ruff.isort]
{% if cookiecutter.project_backend == "flask" %}
known-first-party = ["flaskapp"]
{% endif %}
{% if cookiecutter.project_backend == "fastapi" %}
known-first-party = ["fastapi_app"]
{% endif %}

[tool.black]
line-length = 120
target-version = ["py38"]
{% if cookiecutter.project_backend == "flask" %}
extend-exclude = '''
(
  flaskapp/migrations/
)
'''
force-exclude = '''
# Needed for pre-commit
(
  flaskapp/migrations/
)
'''
{% endif %}

[tool.pytest.ini_options]
addopts = "-ra --cov -vv"
{% if cookiecutter.project_backend == "django" %}
DJANGO_SETTINGS_MODULE = "project.settings"
pythonpath = ["src"]
{% endif %}

[tool.coverage.report]
show_missing = true
