# name: Test
on:
  # when pushed on main
  push:
    branches: [ main ]
  # when a pull request is opened
  pull_request:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
                python-version: 3.12
                cache: 'pip'
        - name: Test
          run: |
                pip install -r requirements.txt
                python -m pytest
